package com.naeblis11.mealplanner.domain

import java.io.File
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertTrue

/**
 * The golden cases in tests/fixtures/parity, generated by the retired Python server and
 * frozen: they are now the reference. Gradle passes their folder in as the
 * `parityDir` system property.
 */
object ParityFixtures {
    private val dir: File by lazy {
        File(
            System.getProperty("parityDir")
                ?: error("parityDir is not set; run the tests through Gradle"),
        )
    }

    fun load(name: String): JsonElement =
        Json.parseToJsonElement(File(dir, name).readText(Charsets.UTF_8))

    /**
     * The cases of a fixture file whose top level is their list. Fails on an empty list: a
     * parity test loops over its cases, so an emptied fixture would otherwise pass vacuously.
     */
    fun cases(name: String): JsonArray = load(name).jsonArray.nonEmpty(name)

    /** Another fixture file, relative to the parity folder (e.g. "../mealmaster/collection.mmf"). */
    fun sibling(relative: String): File = File(dir, relative)
}

/** The named list of cases in a fixture object, as [ParityFixtures.cases]: never missing or empty. */
fun JsonObject.cases(name: String): JsonArray =
    (this[name] ?: throw AssertionError("$name: no such list of cases")).jsonArray.nonEmpty(name)

private fun JsonArray.nonEmpty(name: String): JsonArray {
    assertTrue("$name has no cases", isNotEmpty())
    return this
}

/** A JSON string/number/bool as text, or null for JSON null. */
fun JsonElement.str(): String? = if (this is JsonNull) null else jsonPrimitive.content

val JsonElement.obj: JsonObject get() = jsonObject
